/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IRouterManagement } from "./IRouterManagement";
export type { IUniversalRouter } from "./IUniversalRouter";
