/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export interface IRouterManagementInterface extends utils.Interface {
  functions: {
    "approveRoute(address,bytes,uint256,uint256)": FunctionFragment;
    "collectETHFees()": FunctionFragment;
    "collectTokenFees(bytes1,bytes)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "approveRoute"
      | "collectETHFees"
      | "collectTokenFees"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "approveRoute",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "collectETHFees",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "collectTokenFees",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<BytesLike>]
  ): string;

  decodeFunctionResult(
    functionFragment: "approveRoute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "collectETHFees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "collectTokenFees",
    data: BytesLike
  ): Result;

  events: {};
}

export interface IRouterManagement extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IRouterManagementInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    approveRoute(
      _addrRouter: PromiseOrValue<string>,
      inputs: PromiseOrValue<BytesLike>,
      _amountStart: PromiseOrValue<BigNumberish>,
      _addrStart: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    collectETHFees(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    collectTokenFees(
      command: PromiseOrValue<BytesLike>,
      inputs: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  approveRoute(
    _addrRouter: PromiseOrValue<string>,
    inputs: PromiseOrValue<BytesLike>,
    _amountStart: PromiseOrValue<BigNumberish>,
    _addrStart: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  collectETHFees(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  collectTokenFees(
    command: PromiseOrValue<BytesLike>,
    inputs: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    approveRoute(
      _addrRouter: PromiseOrValue<string>,
      inputs: PromiseOrValue<BytesLike>,
      _amountStart: PromiseOrValue<BigNumberish>,
      _addrStart: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    collectETHFees(overrides?: CallOverrides): Promise<void>;

    collectTokenFees(
      command: PromiseOrValue<BytesLike>,
      inputs: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    approveRoute(
      _addrRouter: PromiseOrValue<string>,
      inputs: PromiseOrValue<BytesLike>,
      _amountStart: PromiseOrValue<BigNumberish>,
      _addrStart: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    collectETHFees(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    collectTokenFees(
      command: PromiseOrValue<BytesLike>,
      inputs: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    approveRoute(
      _addrRouter: PromiseOrValue<string>,
      inputs: PromiseOrValue<BytesLike>,
      _amountStart: PromiseOrValue<BigNumberish>,
      _addrStart: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    collectETHFees(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    collectTokenFees(
      command: PromiseOrValue<BytesLike>,
      inputs: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
