/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IRouterManagement__factory } from "./IRouterManagement__factory";
export { IUniversalRouter__factory } from "./IUniversalRouter__factory";
