/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IRouterManagement,
  IRouterManagementInterface,
} from "../../../contracts/interfaces/IRouterManagement";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_addrRouter",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "inputs",
        type: "bytes",
      },
      {
        internalType: "uint256",
        name: "_amountStart",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_addrStart",
        type: "uint256",
      },
    ],
    name: "approveRoute",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "collectETHFees",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes1",
        name: "command",
        type: "bytes1",
      },
      {
        internalType: "bytes",
        name: "inputs",
        type: "bytes",
      },
    ],
    name: "collectTokenFees",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IRouterManagement__factory {
  static readonly abi = _abi;
  static createInterface(): IRouterManagementInterface {
    return new utils.Interface(_abi) as IRouterManagementInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IRouterManagement {
    return new Contract(address, _abi, signerOrProvider) as IRouterManagement;
  }
}
