/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as base from "./base";
export * as interfaces from "./interfaces";
export { UniversalRouter__factory } from "./UniversalRouter__factory";
