[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib', '../../node_modules']
test = 'test'
cache_path  = 'cache_forge'
allow_paths = ["../../node_modules"]

# See https://github.com/foundry-rs/foundry/issues/4988#issuecomment-1556331314
evm_version = 'shanghai'
